# ex: et sw=2 ts=2:
image: node:16.3.0-alpine

before_script:
  - yarn install

test:
  stage: test
  script:
    - yarn tslint
    - yarn test

pages:
  stage: deploy
  only:
    - master
  script:
    - yarn production
    - gzip --keep public/*
  artifacts:
    paths:
      - public
