#!/bin/sh
yarn --no-progress --silent licenses list > NOTICE.txt
yarn --no-progress --silent licenses generate-disclaimer > third-party.txt
awk -F: '/License/ {print $2}' NOTICE.txt | sort | uniq -c | sort -rn
