const enum Fractal {
    Aetherblade = "Aetherblade",
    AquaticRuins = "Aquatic Ruins",
    CaptainMaiTrinBoss = "Captain Mai Trin Boss",
    ChaosIsles = "Chaos Isles",
    Cliffside = "Cliffside",
    Deepstone = "Deepstone",
    MoltenBoss = "Molten Boss",
    MoltenFurnace = "Molten Furnace",
    Nightmare = "Nightmare",
    ShatteredObservatory = "Shattered Observatory",
    Snowblind = "Snowblind",
    SolidOcean = "Solid Ocean",
    Swampland = "Swampland",
    ThaumanovaReactor = "Thaumanova Reactor",
    TwilightOasis = "Twilight Oasis",
    Uncategorized = "Uncategorized",
    UndergroundFacility = "Underground Facility",
    UrbanBattleground = "Urban Battleground",
    Volcanic = "Volcanic",
}

export default {
     1: Fractal.Volcanic,
     2: Fractal.Uncategorized,
     3: Fractal.Snowblind,
     4: Fractal.UrbanBattleground,
     5: Fractal.Swampland,
     6: Fractal.Cliffside,
     7: Fractal.AquaticRuins,
     8: Fractal.UndergroundFacility,
     9: Fractal.MoltenFurnace,
    10: Fractal.MoltenBoss,
    11: Fractal.Deepstone,
    12: Fractal.Uncategorized,
    13: Fractal.ChaosIsles,
    14: Fractal.Aetherblade,
    15: Fractal.ThaumanovaReactor,
    16: Fractal.TwilightOasis,
    17: Fractal.UndergroundFacility,
    18: Fractal.CaptainMaiTrinBoss,
    19: Fractal.Volcanic,
    20: Fractal.SolidOcean,
    21: Fractal.Swampland,
    22: Fractal.Cliffside,
    23: Fractal.MoltenFurnace,
    24: Fractal.Nightmare,
    25: Fractal.ShatteredObservatory,
    26: Fractal.AquaticRuins,
    27: Fractal.Snowblind,
    28: Fractal.Volcanic,
    29: Fractal.UndergroundFacility,
    30: Fractal.ChaosIsles,
    31: Fractal.UrbanBattleground,
    32: Fractal.Swampland,
    33: Fractal.Deepstone,
    34: Fractal.ThaumanovaReactor,
    35: Fractal.SolidOcean,
    36: Fractal.Uncategorized,
    37: Fractal.Snowblind,
    38: Fractal.ChaosIsles,
    39: Fractal.MoltenFurnace,
    40: Fractal.MoltenBoss,
    41: Fractal.TwilightOasis,
    42: Fractal.CaptainMaiTrinBoss,
    43: Fractal.UndergroundFacility,
    44: Fractal.Uncategorized,
    45: Fractal.SolidOcean,
    46: Fractal.Aetherblade,
    47: Fractal.Cliffside,
    48: Fractal.ThaumanovaReactor,
    49: Fractal.Nightmare,
    50: Fractal.ShatteredObservatory,
    51: Fractal.Snowblind,
    52: Fractal.Volcanic,
    53: Fractal.UndergroundFacility,
    54: Fractal.ChaosIsles,
    55: Fractal.ThaumanovaReactor,
    56: Fractal.Swampland,
    57: Fractal.UrbanBattleground,
    58: Fractal.MoltenFurnace,
    59: Fractal.TwilightOasis,
    60: Fractal.SolidOcean,
    61: Fractal.AquaticRuins,
    62: Fractal.Uncategorized,
    63: Fractal.ChaosIsles,
    64: Fractal.ThaumanovaReactor,
    65: Fractal.Aetherblade,
    66: Fractal.UrbanBattleground,
    67: Fractal.Deepstone,
    68: Fractal.Snowblind,
    69: Fractal.Cliffside,
    70: Fractal.MoltenBoss,
    71: Fractal.Aetherblade,
    72: Fractal.Volcanic,
    73: Fractal.CaptainMaiTrinBoss,
    74: Fractal.Nightmare,
    75: Fractal.ShatteredObservatory,
    76: Fractal.AquaticRuins,
    77: Fractal.Swampland,
    78: Fractal.UrbanBattleground,
    79: Fractal.Uncategorized,
    80: Fractal.SolidOcean,
    81: Fractal.UndergroundFacility,
    82: Fractal.Cliffside,
    83: Fractal.MoltenFurnace,
    84: Fractal.Deepstone,
    85: Fractal.UrbanBattleground,
    86: Fractal.Snowblind,
    87: Fractal.TwilightOasis,
    88: Fractal.ChaosIsles,
    89: Fractal.Swampland,
    90: Fractal.MoltenBoss,
    91: Fractal.Uncategorized,
    92: Fractal.Volcanic,
    93: Fractal.Snowblind,
    94: Fractal.Cliffside,
    95: Fractal.CaptainMaiTrinBoss,
    96: Fractal.Aetherblade,
    97: Fractal.ThaumanovaReactor,
    98: Fractal.ChaosIsles,
    99: Fractal.Nightmare,
    100: Fractal.ShatteredObservatory,
} as IntMap<Fractal>;
